## Problem statement
Day 7 is about splitting beams via splitters '^'. The rules are pretty simple:
1. You start at 'S'
2. You drop a beam '|' below 'S'
3. You move down unless you meet a splitter '^'
4. If you meet a splitter, the two beams adjacent to the splitter are placed
5. Repeat

For part 1 all we have to do is count the number of splits, this can be done straight forwardly by setting rules on where to start 'S' and what happens to '|' cells depending on what's below them.

In [1]:
import numpy as np
with open('sample_input.txt', 'r') as f:
    lines1 = f.read().splitlines()

with open('puzzle_input.txt', 'r') as f:
    lines2 = f.read().splitlines()


def split_counter(lines: list[str]) -> list[list[str]]:
    lines = np.array(lines)
    lines = [[c for c in line] for line in lines]

    #The shadow is used for part 2, to do top down addition of how many times the paths go through there
    shadow = np.zeros(np.shape(lines), dtype=int)
    
    row = 0
    stop = len(lines) - 1
    count = 0
    while row < stop:
        for i in range(len(lines[row])):
            c = lines[row][i]
            
            if c == 'S':
                lines[row+1][i] = '|'

                #Starting point
                shadow[row+1][i] += 1
    
            if c == '|':
                if lines[row+1][i] == '^':
                    lines[row+1][i-1], lines[row+1][i+1] = '|', '|'

                    #Since there's a split, we need to add to the below left and right columns
                    shadow[row+1][i-1] += shadow[row][i]
                    shadow[row+1][i+1] += shadow[row][i]
                    count += 1
    
                else:
                    lines[row+1][i] = '|'

                    #Since no splitting, keep propagating the number downwards
                    shadow[row+1][i] += shadow[row][i]
        row += 1
    
    print(count)
    return lines, shadow
    
lines1, shadow = split_counter(lines1)
for line in lines1:
    print(line)


lines2, shadow2 = split_counter(lines2)

21
['.', '.', '.', '.', '.', '.', '.', 'S', '.', '.', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '.', '.', '|', '.', '.', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '.', '|', '^', '|', '.', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '.', '|', '.', '|', '.', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '|', '^', '|', '^', '|', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '|', '.', '|', '.', '|', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '|', '^', '|', '^', '|', '^', '|', '.', '.', '.', '.']
['.', '.', '.', '.', '|', '.', '|', '.', '|', '.', '|', '.', '.', '.', '.']
['.', '.', '.', '|', '^', '|', '^', '|', '|', '|', '^', '|', '.', '.', '.']
['.', '.', '.', '|', '.', '|', '.', '|', '|', '|', '.', '|', '.', '.', '.']
['.', '.', '|', '^', '|', '^', '|', '|', '|', '^', '|', '^', '|', '.', '.']
['.', '.', '|', '.', '|', '.', '|', '|', '|', '.', '|', '.', '|', '.', '.']
['.', '|', '^', '|', '|', '|', '^', '|', '|', '.', '|', '|', '^', '|', '.']
['.', '|'

## Part 2
Part two looks like a combinatorics problem, basically you're asked to find out how many possible distinct paths there are to the bottom if there's a random chance for it to go left or right when a beam is split. 

To solve it, consider the shadow arrays that were created on the split counter. This basically uses the insight that the ways to get to a cell is always a sum of the number of ways the merging cells have been arrived at. Since this takes care of the problem in a top-down fashion all we need to do is sum the last row to get the number of different paths.

In [2]:
for line in shadow:
    print(line)

total = sum(shadow[-2])

print(f"Sample input solution is {total}")

total = sum(shadow2[-2])
print(f"Puzzle input solution is {total}")

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 2 0 1 0 0 0 0 0]
[0 0 0 0 0 1 0 2 0 1 0 0 0 0 0]
[0 0 0 0 1 0 3 0 3 0 1 0 0 0 0]
[0 0 0 0 1 0 3 0 3 0 1 0 0 0 0]
[0 0 0 1 0 4 0 3 3 1 0 1 0 0 0]
[0 0 0 1 0 4 0 3 3 1 0 1 0 0 0]
[0 0 1 0 5 0 4 3 4 0 2 0 1 0 0]
[0 0 1 0 5 0 4 3 4 0 2 0 1 0 0]
[0 1 0 1 5 4 0 7 4 0 2 1 0 1 0]
[0 1 0 1 5 4 0 7 4 0 2 1 0 1 0]
[ 1  0  2  0 10  0 11  0 11  0  2  1  1  0  1]
[ 1  0  2  0 10  0 11  0 11  0  2  1  1  0  1]
Sample input solution is 40
Puzzle input solution is 15093663987272


## Visualisation
Let's visualise how they look for fun!

Starting with the sample input.

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

mas = shadow == 0
plt.figure(figsize=(6, 6))
sns.heatmap(shadow, vmin = 1, xticklabels= False, cmap = 'hot', yticklabels = False, mask = mas, cbar_kws={"shrink": 0.4})
plt.savefig('sample.png')
plt.close()

plt.figure(figsize=(10, 10))
sns.heatmap(shadow2, xticklabels= False, yticklabels = False, cmap= 'cividis', cbar = False, norm=mcolors.LogNorm())
plt.savefig('puzzle.png')
plt.close()

### Sample input heatmap:
---

<img src='sample.png' />

### Puzzle input heatmap:
---

<img src='puzzle.png' />